# .readthedocs.yaml configuration file
# For more details see: https://docs.readthedocs.io/en/stable/config-file/v2.html

# Required version of the configuration file
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Build documentation in the "docs" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optional: If you use Markdown, you need to install standard dependencies
python:
  install:
    - requirements: docs/requirements.txt

# Specify the formats to build
formats:
  - pdf
  - epub
